### PR TITLE
linux-mainline: Add back eMMC support for Nanopi Neo Air

### PR DESCRIPTION
**Pull request by floion**
Signed-off-by: Florin Sarbu <florin@resin.io>

### CODE REVIEW

**Comment by floion** [comment]
@naguirre @ebutera @slapin

**Comment by floion** [comment]
Hi @slapin any update here?

**Comment by floion** [comment]
Hi @naguirre @ebutera can you guys look at this PR?

**Comment by ebutera** [comment]
sorry, i didn't receive the notification email, merging now

**Pull request merged**
