### PR TITLE
add LAYERSERIES_COMPAT declaration

### PR DESCRIPTION
**Pull request by martingkelly**
In current Yocto master, it's now a warning not to include
LAYERSERIES_COMPAT in layer.conf. See below for more information:

https://www.yoctoproject.org/docs/latest/mega-manual/mega-manual.html#var-LAYERSERIES_COMPAT

Add this information for all current development and stable releases.

Signed-off-by: Martin Kelly <mkelly@xevo.com>

### CODE REVIEW

**Comment by diegorondini** [comment]
I've tested the patch and it fixes the warning for me. Thanks

**Comment by diegorondini** [comment]
Tested-by: Diego Rondini diego.rondini@kynetics.com

**Comment by koenkooi** [comment]
does master actually work all the way back down to morty?

**Comment by geomatsi** [comment]
@koenkooi 
Basic support including kernel and u-boot works fine with morty/rocko/sumo. Though I can not comment on graphics packages and gstreamer plugin since I have never used them.

**Pull request merged**
