### PR TITLE
added a20som support to pyA20

### PR DESCRIPTION
**Pull request by xpete**

### CODE REVIEW

**Comment by xpete** [comment]
I still get this error when I add pyA20 to my image after adding the A20-SOM support.

ERROR: image-1.0-r3 do_rootfs: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:license_create_manifest(d)
     0003:
File: '/home/username/Projects/build/../poky/meta/classes/license.bbclass', lineno: 48, function: license_create_manifest
     0044:    pkg_dic = {}
     0045:    for pkg in sorted(image_list_installed_packages(d)):
     0046:        pkg_info = os.path.join(d.getVar('PKGDATA_DIR', True),
     0047:                                'runtime-reverse', pkg)
 *** 0048:        pkg_name = os.path.basename(os.readlink(pkg_info))
     0049:
     0050:        pkg_dic[pkg_name] = oe.packagedata.read_pkgdatafile(pkg_info)
     0051:        if not "LICENSE" in pkg_dic[pkg_name].keys():
     0052:            pkg_lic_name = "LICENSE_" + pkg_name
Exception: OSError: [Errno 2] No such file or directory: '/home/username/Projects/build/tmp/sysroots/olinuxino-a20som/pkgdata/runtime-reverse/pya20'

ERROR: image-1.0-r3 do_rootfs: Function failed: license_create_manifest
ERROR: Logfile of failure stored in: /home/username/Projects/build/tmp/work/olinuxino_a20som-poky-linux-gnueabi/image/1.0-r3/temp/log.do_rootfs.16867
ERROR: Task 9 (/home/username/Projects/build/../meta-private/recipes-private/images/image.bb, do_rootfs) failed with exit code '1'
`

**Comment by ebutera** [comment]
do you mean that your patch fixes that error? or do you get that error after your patch?

**Comment by xpete** [comment]
The A20-SOM support is missing. The patch fixes that.
I get the error after my patch.
Just tried to create an image for olinuxino-a20 and I get the same error. I guess it's a recipe error.
I think you can apply this patch in krogoth, morty and master and I'am going to open a new issue.

**Comment by xpete** [comment]
The last commit fixes the remaining issues. fully tested and working :)

**Comment by xpete** [comment]
Just tested in morty and it's working too.

**Comment by ebutera** [comment]
applied to morty and master too, thanks!

**Pull request merged**
