### PR TITLE
New device Orange PI lite

### PR DESCRIPTION
**Pull request by buldo**
I tested it with mainline 6.1.9

### CODE REVIEW

**Review by nandra — APPROVED** [review]

**Comment by nandra** [comment]
Thanks, merged.

**Comment by ludiazv** [comment]
Hi @buldo ,
I'm trying to use this board an compile with 6.x kernel but I've got this warning:
```
$ bitbake -c compile virtual/kernel
Loading cache: 100% |##############################################################################################################################################################################################| Time: 0:00:01
Loaded 4567 entries from dependency cache.
WARNING: preferred version 6.1.% of linux-mainline not available (for item virtual/kernel)
WARNING: versions of linux-mainline available: 5.10.166 5.15.91 5.4.230
NOTE: Resolving any missing task queue dependencies
WARNING: preferred version 6.1.% of linux-mainline not available (for item kernel-image-uimage)
WARNING: versions of linux-mainline available: 5.10.166 5.15.91 5.4.230
WARNING: preferred version 6.1.% of linux-mainline not available (for item kernel-base)
WARNING: versions of linux-mainline available: 5.10.166 5.15.91 5.4.230
WARNING: preferred version 6.1.% of linux-mainline not available (for item kernel-image)
WARNING: versions of linux-mainline available: 5.10.166 5.15.91 5.4.230
```

It compiles but it fallbacks to version 5.15.91. Any idea on how to change this behaviour.

My layers are pointing to "mickledore" but if i change "langdale" for example nothing change.

on the other hand if compile for "orange-pi-zero2" board the kernel 6.1.9 is selected.

**Comment by nandra** [comment]
@ludiazv are you sure you're on master? On master we have:
```
PREFERRED_VERSION_linux-mainline ?= "6.1.%"
```

**Comment by ludiazv** [comment]
Yes. check this out:
```sh
bitbake -e virtual/kernel | grep ^PREFERRED_VERSION_linux
PREFERRED_VERSION_linux-libc-headers="6.1%"
PREFERRED_VERSION_linux-mainline="6.1.%"
PREFERRED_VERSION_linux-yocto="6.1%"
PREFERRED_VERSION_linux-yocto-rt="6.1%"
```
But the build process fallbacks to 5.15 showing the warnings on in my previous post. See the tmp/work area:

```sh
$ ls tmp/work/orange_pi_lite-poky-linux-musleabi/linux-mainline/
5.15.91-r0
```
the kernel compiles but not the version I expected by the comments from @buldo.

I found this problem while I was porting other board and wanted to check out If I can use 6.x appart from the oranpi zero 2.

**Comment by buldo** [comment]
Looks very strange. My PR only adds one file that specified device tree file and config from u-boot

**Comment by ludiazv** [comment]
> Looks very strange. My PR only adds one file that specified device tree file and config from u-boot

Yes thats why I chose your board definition as it simple and in theory would work with the preferred version.

**Pull request merged**
