### PR TITLE
u-boot_2018.03.bb: Enable eMMC support for Nanopi Neo Air

### PR DESCRIPTION
**Pull request by floion**
Signed-off-by: Florin Sarbu <florin@resin.io>

### CODE REVIEW

**Comment by floion** [comment]
@naguirre @ebutera @slapin

**Comment by slapin** [comment]
Hi all!
I will be able to look at these on weekend. If nobody merges/rejects these
before.

**Comment by floion** [comment]
Thanks. In case these get merged, will you guys automatically add them to master also? Or shall I create the PR for master?

**Comment by floion** [comment]
Hi @slapin any update here?

**Comment by floion** [comment]
@t did you guys have a chance to look over this?

**Comment by slapin** [comment]
Hi Florin, sorry was too busy with work. Will look at it ASAP.

**Comment by floion** [comment]
Hi @slapin have you had any time to look into these PRs?

**Comment by floion** [comment]
Hi @naguirre @ebutera can you guys look at this PR?

**Comment by ebutera** [comment]
yes please, you can make a PR to merge it on master too

**Pull request merged**
