### PR TITLE
u-boot: upgrade to 2018.09

### PR DESCRIPTION
**Pull request by geomatsi**
Bump u-boot version to 2018.09.
Notes:
- drop pylibfdt fixup: the issue has been fixed in upstream u-boot
- add bison and flex as depenedencies
- update license info
- update patch for nanopi-neo-air

Primary motivation for this update was unaligned access error on orange-pi-zero board with u-boot v2018.03 built using gcc-8.2:
```
Starting kernel ...

data abort
pc : [<4ff9f5cc>]          lr : [<4ff73f03>]
reloc pc : [<4a02c5cc>]    lr : [<4a000f03>]
sp : 4bf4e040  ip : 4bf537ea     fp : 42000040
r10: 4bf88a0c  r9 : 4bf52ee0     r8 : 00000400
r7 : 00000000  r6 : 40008000     r5 : 49ff9000  r4 : 00000000
r3 : 49ff9000  r2 : 49ff9000     r1 : 00000000  r0 : 00000000
Flags: nZCv  IRQs off  FIQs off  Mode UK6_32
Resetting CPU ...

resetting ...
```
I would suggest to bump u-boot version rather than add patch needed to build older u-boot with newer toolchain.

Regards,
Sergey

### CODE REVIEW

**Comment by macpijan** [comment]
This recipe works well for me on orange pi zero.

**Comment by geomatsi** [comment]
Hello @macpijan ,
Could you please clarify your comment. Do you mean that you don't see any issues with u-boot v2018.03 built using gcc-8.2 ?

Regards,
Sergey

**Comment by macpijan** [comment]
@geomatsi Yes, sorry. I mean I have tested your recipe and it works fine for me :+1:

**Comment by macpijan** [comment]
I am not aware of the problems with the v2018.03. I wanted to do the U-Boot upgrade for other reasons. But I found your work and decided to test it instead.

**Comment by aragua** [comment]
Instead of upgrading version, wy don't you just use OE/yocto default recipe of uboot with a bbappend? It can be easier to maintain.

**Comment by geomatsi** [comment]
Well, we need several additional pieces, e.g. board preferences, ATF bits for arm64. That probably can be done in the form of bbappend, but no one tried it yet.

**Pull request merged**
