### PR TITLE
Make the kernel more usable, patch set #2

### PR DESCRIPTION
**Pull request by koenkooi**
The last patchset for today, my coffeebreak has ended :)

This enables wifi and bluetooth but the most important part is that the serial console now works again when using systemd!

### CODE REVIEW

**Comment by ebutera** [comment]
was disabling CONFIG_DEBUG_FS really wanted?

I find /sys/kernel/debug really useful, expecially for *cute nonsense embedded hacks™*

**Comment by koenkooi** [comment]
No, debugfs was turned off by 'make menuconfig' for some reason. I'll send a pull request later today to reenable it since I need it as well :)

**Comment by koenkooi** [comment]
I just checked on the running kernel:

root@olinuxino-a20micro:~# zcat /proc/config.gz | grep -i debug_fs
CONFIG_DEBUG_FS=y

root@olinuxino-a20micro:~# uname -a
Linux olinuxino-a20micro 4.1.2 #2 SMP Thu Jul 30 10:55:02 CEST 2015 armv7l GNU/Linux

So it looks like something in wifi requires debugfs, which 'make savedefconfig' takes as a sign to drop it, since it is now the default value.

**Comment by ebutera** [comment]
strange, so if for example one day you disable wifi (or whatever it is that is pulling it) you will disable debugfs too....
good to know to not use savedefconfig for testing/development!

**Comment by koenkooi** [comment]
Sort off, the .config will have it turned on, so disabling wifi will bring it back in 'defconfig' since it will then be a non-default feature. At least that's what the theory is :)

**Pull request merged**
