### PR TITLE
Add Orange Pi Prime machine support

### PR DESCRIPTION
**Pull request by alperak**
- Ethernet, WiFi, Bluetooth, USBs are working fine but HDMI is working until U-Boot loading the kernel. Then it stop working.
- Tested with core-image-base and kernel mainline 6.6.28

### CODE REVIEW

**Comment by nandra** [comment]
Looks good to me juts one small nitpick. Please post update version so it can be merged. Thanks.

**Comment by alperak** [comment]
I don't quite understand what you mean by "Please send the update version". If you asked me to specify the kernel version, I have updated the commit and comment.

**Comment by nandra** [comment]
> I don't quite understand what you mean by "Please send the update version". If you asked me to specify the kernel version, I have updated the commit and comment.

I mean see review comments and post updated version with those comments. Thanks.

**Comment by alperak** [comment]
There might be a permission issue or something else that prevents me and others from seeing those comments. Can you please share a permalink to those? Or possibly comment again?

**Comment by nandra** [comment]
You should see those messages (those are comments):

image

**Comment by alperak** [comment]
It says "Pending" in your comments, I think that's why I can't see. https://github.com/orgs/community/discussions/10369

Anyway, I will make the changes accordingly screenshot and push it when I'm available.

**Review by nandra — APPROVED** [review]

**Comment by nandra** [comment]
Thanks @alperak

**Pull request merged**
