### PR TITLE
tslib: remove

### PR DESCRIPTION
**Pull request by twoerner**
tslib has been removed from openembedded-core, therefore this bbappend is no
longer required.

references:
http://lists.openembedded.org/pipermail/openembedded-core/2016-August/124995.html
http://lists.openembedded.org/pipermail/openembedded-core/2016-August/126022.html

Signed-off-by: Trevor Woerner twoerner@gmail.com

### CODE REVIEW

**Comment by ebutera** [comment]
after some discussion it was decided that tslib was going to be added in meta-oe, in the readme we state that meta-oe is required so i wouldn't remove it.

Well i don't know if we REALLY require meta-oe today, and if tslib version is really 1.1, but that's another story :D

**Comment by twoerner** [comment]
Okay, I'll look into this some more.

At this point, with tslib removed, I can successfully build core-image-minimal using the master branch for cubietruck needing only openembedded-core and meta-sunxi. I'll try some other combinations and see what happens.

**Comment by ebutera** [comment]
if we don't need meta-oe "dependency" we can remove it from the readme, but i think that resistive touchscreens are very common so instead of deleting it i would disable it (for ex. rename to tslib_1.1.bbappend.disabled) and add a note on the readme.

**Comment by twoerner** [comment]
I'm not an expert on what's going on with tslib, but it looks like there were competing tslibs and the one that was put into meta-openembedded is not the one for which the meta-sunxi's bbappend had been written.

meta-sunxi's bbappend is for a tslib_1.1 recipe. meta-openembedded has a xf86-input-tslib_0.0.6. So it's questionable whether or not meta-sunxi's bbappend even applies.

If a user wants tslib in their image they can simply include it in their image. The only question is, does meta-sunxi need to tweak it for use on AllWinner chips?

**Comment by ebutera** [comment]
> The only question is, does meta-sunxi need to tweak it for use on AllWinner chips?

exactly, and i don't know :)

apart from that, xf86-input-tslib should be only an xorg driver and has no tool for calibration. A patch was posted to add tslib to meta-oe:
http://lists.openembedded.org/pipermail/openembedded-devel/2016-September/108945.html
http://lists.openembedded.org/pipermail/openembedded-devel/2016-September/109151.html

**Comment by nandra** [comment]
Do we still need this? Actually tslib is disabled. I was thinking as only patch is used for A13-OLinuXino board so extend recipe only for this board type (maybe dependency on tslib only if touchscreen is in MACHINE_FEATURES)? Thanks.

**Comment by twoerner** [comment]
With https://github.com/linux-sunxi/meta-sunxi/pull/166 having been applied, this pull request can be closed.

**Comment by nandra** [comment]
@twoerner thanks.

**Pull request closed without merging**
