### PR TITLE
Add mainline linux

### PR DESCRIPTION
**Pull request by Noxenious**
Add recipe and configuration files for mainline linux.

Signed-off-by: Jens Lucius <info@jenslucius.com>

### CODE REVIEW

**Comment by whirm** [comment]
The package builds, but the sunxi image recipe still needs updating to copy the DTB.

I will create a PR with the patches I already have on my branch for that.

re this recipe: On mine I used ```make sunxi_defconfig``` instead of having 11 identical copies of defconfig and people can still add their own defconfig on their layer if they want.

**Comment by ebutera** [comment]
please as @whirm said it's better to just use the sunxi_defconfig instead of adding those files, it's much easier to maintain

**Comment by Noxenious** [comment]
The devicetree should be pulled automatically into the filesystem. I´ll test if it works.

Do you mean adding the sunxi_defconfig as defconfig for all boards or do a make sunxi_defconfig within the recipe?

**Comment by ebutera** [comment]
yes i mean "make sunxi_defconfig" within the recipe, it should be something like
do_configure () {
  oe_runmake sunxi_defconfig
}

i've seen something like that in other recipes, i can't check right now where you can find it

**Comment by Noxenious** [comment]
Ok i tested and added it.

There are still some problems with including the devicetree file in the filesystem. I´ll look into it tomorrow

**Comment by whirm** [comment]
@Noxenious if you override ```do_configure``` like this, you are nullifying everything done in ```linux.inc:do_configure_prepend()```

**Comment by naguirre** [comment]
Not related to the current PR, but I wanted to do that for a long time but never take the time : I think that we should avoid the long list of compatibles machines, and set only sun5i or sun7i, as they did in meta-fsl-arm with mx6, mx5, ...
They added a SOC_FAMILLY variable to setup this variable, and in linux and u-boot recipes, they then put the  COMPATIBLE_MACHINE = "(mxs|mx3|mx5|mx6)"
Not sure what they did exactly, but i will try to do the same.

**Comment by Noxenious** [comment]
The linux.inc is modifying the file defconfig which does not exist using oe_runmake sunxi_defconfig. I´ll come up with something else.

**Comment by Noxenious** [comment]
as far as a little grep shows the SOC_FAMILY is set within the machine configs, also set in the conf/machine/include/imx-base.inc and there is a class for this:
classes/fsl-dynamic-packagearch.bbclass

**Comment by Noxenious** [comment]
Would there be a problem to switch to yocto style kernel config? This seems the easiest way to solve all kernel recipe problems? This would limit the recipe to yocto, is it used by any other systems?

**Comment by naguirre** [comment]
What's yocto style kernel config ?

**Comment by Noxenious** [comment]
For the recipe it´s just requiring recipes-kernel/linux/linux-yocto.inc.

It adds a few tasks, inherits device tree, kernel-yocto.class, which in turn makes it possible to use kernel configuration fragments and uses out of tree build.

To include the defconfig dynamically and keep the linux.inc I see two ways at the moment:

1) Just include a file defconfig with the sunxi_defconfig values, which has to be updated from time to time and just be done with it

2) Switch to Linux Yocto, grab sunxi_defconfig dynamically from kernel directory and make it possible to add configuration fragments with the downside of adding a little bit more complexity at the background.

Any wishes?

**Comment by ebutera** [comment]
i'd say for now to just go with 1), include a single defconfig for all machines, after all it has to be updated only once when a new kernel version is added.
The SOC_FAMILY feature would be great too, but if nobody has time to do it right now i wouldn't stop the new kernel recipe from being added just for that.

**Comment by naguirre** [comment]
Ok,  like the way yocto configure the kernel, with fragments.
As @ebutera said go with 1) for this PR. And we will see for 2) after the switch to SOC_FAMILY

I already did the changes yesteday, for SOC_FAMILY and it's seems to work correctly, but i need to test a bit more before pushing changes.

**Comment by Noxenious** [comment]
Ok this should work now. I have tested it with the latest mainline u-boot push request on two boards. For now the default is set to the sunxi-kernel (see discussion in u-boot mainline request).

Any comments? If a kernel fragments config is needed later, just let me know.

**Pull request merged**
