### PR TITLE
Bump kernel and U-Boot

### PR DESCRIPTION
**Pull request by jlucius**
Bump mainline kernel to 4.4.3 (from 4.1.15)
Bump git kernel to 4.5 rc6 (from 4.4 rc5)
Bump U-Boot to 2016.01 (from 2015.10)

### CODE REVIEW

**Comment by slapin** [comment]
What boards was tested with this PR?

**Comment by slapin** [comment]
I just interested if it breaks olinuxinos :)

**Comment by ebutera** [comment]
i tested 4.4 kernel and u-boot 2016.01 on lime2 (not from this pull request) and they works, and jethro branch will stay on 4.1 (at least for now), so it should be ok.
@jlucius i see only one problem, _git version has DEFAULT_PREFERENCE = 1 now.

**Comment by net147** [comment]
Can you please explicitly set SRC_URI instead of appending?

```
SRC_URI = "git://git.denx.de/u-boot.git;branch=master \
           file://boot.cmd"
```

The SRC_URI should be explicitly set rather than appended otherwise it fails to build with OE-core master branch. The master branch has a patch added for am335x in u-boot.inc that isn't needed for sunxi.

**Comment by jlucius** [comment]
Ok I hope this should address any issues

**Comment by jlucius** [comment]
Oh and by the way, I always test with an A20-Lime, core-image-minimal

**Comment by jlucius** [comment]
Updated now with the latest kernel and U-Boot versions. Can this be merged?

**Pull request merged**
