### PR TITLE
Support for NextThingCo C.H.I.P (sun5i r8 chip)

### PR DESCRIPTION
**Pull request by soderstrom-rikard**
Most parts of this pull request is kinda straight forward. However the changes to `classes/sdcard_image-sunxi.bbclass` should probably be explained.

I also include a short usage guide, since there are some manual steps with the CHIP-tools needed. Even thou a pull request probably isn't the best place for this. I think it is important to highlight this. I will try having an update guide in nexthingco forums, here
https://bbs.nextthing.co/t/yocto-project-an-initial-teaser-release/833

Thoughts? Feedback?
##### SDCARD and FEX files

The nextthingco chip does not have an sdcard slot nor does it use fex files. Therefor I made it like a switch, where it defaults to the standard behavior of having a sdcard and fex files. But in the `conf/machine/chip.conf`we ensure that for the chip machine it is not included by explicitly adding

```
SUNXI_BOARD_FEX_IMAGE        ?= ""
SUNXI_BOARD_FEX_IMAGE_DEPLOY ?= ""
```

Personally I haven't seen a more reliable way introducing this change, but if someone knows a better strategy please feel free to tell me. 
##### CHIP Tools

Currently the CHIP tools is hardwired for the buildroot images. In particular the rootfs partition name.
So that would need to be changed in order to run on target. I have a commit for this here
https://github.com/soderstrom-rikard/CHIP-tools/commit/37282e573e3668f70ac1a3c352ce61e6e24d5b60

``` diff
    echo "nand write.raw.noverify $SPL_MEM_ADDR 0x400000 $PADDED_SPL_SIZE" >> "${UBOOT_SCRIPT_SRC}"

    echo "nand write $UBOOT_MEM_ADDR 0x800000 $PADDED_UBOOT_SIZE" >> "${UBOOT_SCRIPT_SRC}"
-   echo "setenv bootargs root=ubi0:rootfs rootfstype=ubifs rw earlyprintk ubi.mtd=4" >> "${UBOOT_SCRIPT_SRC}"
-   echo "setenv bootcmd 'if test -n \${fel_booted} && test -n \${scriptaddr}; then echo '(FEL boot)'; source \${scriptaddr}; fi; mtdparts; ubi part UBI; ubifsmount ubi0:rootfs; ubifsload \$fdt_addr_r /boot/sun5i-r8-chip.dtb; ubifsload \$kernel_addr_r /boot/zImage; bootz \$kernel_addr_r - \$fdt_addr_r'" >> "${UBOOT_SCRIPT_SRC}"
+   echo "setenv bootargs root=ubi0:chip-rootfs rootfstype=ubifs rw earlyprintk ubi.mtd=4" >> "${UBOOT_SCRIPT_SRC}"
+   echo "setenv bootcmd 'if test -n \${fel_booted} && test -n \${scriptaddr}; then echo '(FEL boot)'; source \${scriptaddr}; fi; mtdparts; ubi part UBI; ubifsmount ubi0:chip-rootfs; ubifsload \$fdt_addr_r /boot/sun5i-r8-chip.dtb; ubifsload \$kernel_addr_r /boot/zImage; bootz \$kernel_addr_r - \$fdt_addr_r'" >> "${UBOOT_SCRIPT_SRC}"
   echo "setenv fel_booted 0" >> "${UBOOT_SCRIPT_SRC}"

   echo "echo Enabling Splash" >> "${UBOOT_SCRIPT_SRC}"
```
##### Configuration and build
1. Setup bblayers normally for meta-sunxi.
2. Set `MACHINE` in `conf/local.conf` to `chip`
3. Build with `bitbake core-image-minimal`
4. Copy images to CHIP-tools/.firmware/images

The copying step needs to match the names `chip-fel-flash.sh` from CHIP-tools uses

So for example

``` bash
cd CHIP-tools/.firmware/images
${YOCTO-CHIP-BUILDDIR}/tmp/deploy/images/chip/core-image-minimal-chip.ubi rootfs.ubi
${YOCTO-CHIP-BUILDDIR}/tmp/deploy/images/chip/zImage-sun5i-r8-chip.dtb sun5i-r8-chip.dtb
${YOCTO-CHIP-BUILDDIR}/tmp/deploy/images/chip/sunxi-spl.bin .
${YOCTO-CHIP-BUILDDIR}/tmp/deploy/images/chip/u-boot-dtb.bin .
${YOCTO-CHIP-BUILDDIR}/tmp/deploy/images/chip/uboot-env.bin .
${YOCTO-CHIP-BUILDDIR}/tmp/deploy/images/chip/zImage .
```

Is one way to do this.

### CODE REVIEW

**Comment by jlucius** [comment]
I think I would try to not build fex any more as default is now to build mainline which don't use fex any more.

Suggestions:
1) Set default variables to empty and set in other boards than chip (would default to same behavior as before, new boards would not need to set it)
2) What would happen if linux-sunxi depends on sunxi-board-fex? I that case for kernel 3.4 the fex should be build (and that is where it is needed). Just need to make sure it is deployed before building the image (but is that step really needed if it depends? Should be included automatically? I am not sure if I have time to try this solutions but maybe somebody other can?) Should solve the problem for this and the other pull request.

I see no problems with the other changes as they mostly set up special chip kernel and u-boot (I guess mainline is not supporting it yet?)

**Comment by ebutera** [comment]
I agree that the default should be to not build fex, and have those machine that still need it to set it.

And i was wondering too, are those kernel and u-boot repositories so different from mainline?

**Comment by ebutera** [comment]
anyway even if you need a custom kernel, i think you shouldn't set:

COMPATIBLE_MACHINE = "(chip|sunxi)"

but just chip (and you have another compatible_machine line above that, please remove it).

You don't need to add kernel-devicetree to machine conf image_install_append, kernel recipe already RDEPENDS on it.
mtd-utils shouldn't be there too, unless there is a strong reason that i can't think of.
(Actually i don't even know if IMAGE_INSTALL exists when the machine conf is parsed)

**Comment by radolin** [comment]
I think the idea to move the sunxi-board-fex dependency to the linux-sunxi kernel recipe is the most logical solution. It's in fact the sunxi kernel which depends on the fex, like for the mainline kernel it's the kernel recipe which pulls in the device tree dependency.

**Comment by jlucius** [comment]
I had a little time to make a patch according to my suggestions and tested a clean build with sunxi-kernel and it correctly builds the fex file and deploys it into the image. If my patch is accepted maybe you could change your pull to fit it? Should make it a little bit easier.

I had a look at the kernel and u-boot repositories for chip and I don´t like special recipes for either but the changes are so extensive that any other solution does not make sense. I think the compatible machine for sunxi is there because also other boards could benefit from the changes to the mainline kernel?

**Comment by ebutera** [comment]
@soderstrom-rikard  have a look at #127 
about kernel and u-boot, if they are that different then let's just use the custom recipes.

**Comment by soderstrom-rikard** [comment]
Thank you all for all the wonderful feedback.

I will start looking into this tomorrow after work.

In regard to kernel and u-boot, I think they only added sunxi-r8-chip.dts files. Otherwise they are the same as mainline.

> (Actually i don't even know if IMAGE_INSTALL exists when the machine conf is parsed)

I've been a bit confused about this part myself. I first found it on slide 170 of [Free Electrons: Yocto Project and OpenEmbedded Training](http://free-electrons.com/doc/training/yocto/yocto-slides.pdf). Setting `IMAGE_INSTALL =` directly (or with +=) seems to have no effect, but when using `IMAGE_INSTALL_append` it does. This has been confusing me, but I haven't looked into it that much yet.

> You don't need to add kernel-devicetree to machine conf image_install_append, kernel recipe already RDEPENDS on it.
mtd-utils shouldn't be there too, unless there is a strong reason that i can't think of.

`mtd-utils` is definitely an extra, I will remove that. But the others I seem to need in order to get the kernel and device tree properly installed in the rootfs. But I guess technically it is enough that it is built, and that this is more a matter of me being lazy (aka wanting something that works seamlessly with the CHIP-tools). I will happily change it.

Cheerio
Rikard

**Comment by radolin** [comment]
> In regard to kernel and u-boot, I think they only added sunxi-r8-chip.dts files. Otherwise they are the same as mainline.

Last time I checked there was at least the audio codec support which was not in mainline yet.
 
>     (Actually i don't even know if IMAGE_INSTALL exists when the machine conf is parsed)
> 
> I've been a bit confused about this part myself. I first found it on slide 170 of Free Electrons: Yocto Project and OpenEmbedded Training. Setting IMAGE_INSTALL = directly (or with +=) seems to have no effect, but when using IMAGE_INSTALL_append it does. 

That's because += and .= append operators are applied immediately, but the _append (so called Override Style Syntax) is 'deferred until after parsing completes rather than being immediately applied'. 

> 
>     You don't need to add kernel-devicetree to machine conf image_install_append, kernel recipe already RDEPENDS on it.
>     mtd-utils shouldn't be there too, unless there is a strong reason that i can't think of.
> 
> mtd-utils is definitely an extra, I will remove that. But the others I seem to need in order to get the kernel and device tree properly installed in the rootfs.

kernel-image will be pulled by kernel.bbclass, this will also get kernel-devicetree, as we have it in RDEPENDS_kernel-base in the kernel recipe. Modules are usually put in as a MACHINE_EXTRA_RRECOMMENDS, but we already have that in sunxi.inc.

I would say you can safely delete your complete IMAGE_INSTALL_append .... line.

**Comment by soderstrom-rikard** [comment]
Thank you @radolin for your input.

I started working on some of the points made, however I won't be able to finish this today, to tired from work.

**Comment by jlucius** [comment]
Just about the difference between mainline and nextthingco, the DTS is already in the 4.4 tree, but there are a lot of NAND patches that are not mainlined.

**Comment by ebutera** [comment]
i'll leave to @soderstrom-rikard to decide if he prefers a custom kernel recipe or use mainline, but another solution could be to customize the SRC_URI in mainline recipe:

SRC_URI += "https://www.kernel.org/pub/linux/kernel/v4.x/linux-${PV}.tar.xz \
        file://defconfig \
        "
+SRC_URI_chip = "whatever.... \
+       file://defconfig \
+        "

(btw i think "+=" is wrong, it should be "=")

**Comment by jlucius** [comment]
the += should be replaced by =

I will bump the kernels this week and replace it.

**Comment by soderstrom-rikard** [comment]
@ebutera, I do like the idea of using `SRC_URI_chip`.

I'm guessing this should go into the `linux_git.bb`?
I don't see it fitting in `linux_4.1.7.bb` (mostly since its a newer kernel version)

**Comment by ebutera** [comment]
yes of course the kernel version should match, so wait for the new versions from jlucius and then add it where appropriate

**Comment by jlucius** [comment]
Well there is another problem. The linux_4.1.10.bb is default and uses a tar files from kernel.org and has 
S = "${WORKDIR}/linux-${PV}"

The linux_git.bb uses git and has
S = "${WORKDIR}/git"

If the SRC_URI is overwritten by the chip recipe, the default kernel recipe with tar files is overwriten and there the source definition is wrong for a git kernel source. Any idea how to do this correctly?

I think I have time to bump the kernels on the weekend

**Comment by soderstrom-rikard** [comment]
@radolin 

> I would say you can safely delete your complete IMAGE_INSTALL_append .... line.

When I remove this line, the devicetree.dtb, zImage and lib/modules is removed from the final rootfs. I remember having this issue before, why I first tried extending the core-image-minimal recipe into a "chip-image-minimal", later I found the `IMAGE_INSTALL_append` and then I could remove this extra recipe. 

I wonder if we are confusing the definition of [RDEPENDS](http://www.yoctoproject.org/docs/1.8/ref-manual/ref-manual.html#var-RDEPENDS) somehow. 

@jlucius 

I also noticed this, sadly I don't know what the proper way to handle this is. I will see if I can find something during the weekend, unless someone knows a good solution.

---

Disregarding the two above problems, things should be updated now. 

Please let me know if I missed something.

Cheerio
Rikard

**Comment by ebutera** [comment]
yes just use the custom kernel recipe (as you did).
One last thing: are you sure chip/stable is the right branch? It's based on 4.2.0rc1 and i don't think it will be ever updated, while nextthing/4.3/chip is based on 4.3.0

**Comment by soderstrom-rikard** [comment]
@ebutera 

Good point, I will change that tomorrow.

**Comment by soderstrom-rikard** [comment]
The issues I had has been resolved.

Essentially merging my changes of CHIP-tools with the *chip/next* branch and updating `recipes-bsp/u-boot/u-boot-chip_2015.10.bb` to use the *sunxi-spl-with-ecc* solved the issues at hand.

```diff
 PE = "1"
 
 # sunxi-spl.bin
-SUNXI_SPL_IMAGE   = "sunxi-spl"
+SUNXI_SPL_IMAGE   = "sunxi-spl-with-ecc"
 SUNXI_SPL_BINARY  = "${SUNXI_SPL_IMAGE}.bin"
 SUNXI_SPL_SYMLINK = "${SUNXI_SPL_BINARY}-${MACHINE}"
 
```

Cheerio
Rikard Söderström

**Comment by slapin** [comment]
If you want to just set your custom partition name, you don't need separate u-boot recipe,
if mainline u-boot is OK with you you can just use your own machine-specific boot.scr and modify it to your needs

**Comment by agherzan** [comment]
https://github.com/agherzan/meta-chip/commits/master was tested and already used in yocto community.

**Comment by soderstrom-rikard** [comment]
I think its time to close this one.

Just like @agherzan points out there is a meta-chip layer (and I also noticed there are two meta-chip layers agherzan/meta-chip#8)

Cheerio
soderstrom

**Pull request closed without merging**
