### PR TITLE
[RFC] [DO NOT MERGE] Add Beelink GS1 Board

### PR DESCRIPTION
**Pull request by clementperon**
Hi,

I'm planning to add my board based on H6. For this i need to switch to more recent upstream ATF.

Also how do you make a difference between sun50i A64 and sun50i H6?

Shoud I change the SOC_FAMILY to sun50iw1p1 for A64?

### CODE REVIEW

**Comment by nandra** [comment]
@clementperon thanks for patch. I'll try to build for bananapi (also A64) to see if it works. Thanks.

**Comment by clementperon** [comment]
@nandra in the latest patch I have change the family 
PLATFORM:sun50i = "sun50i_h6"
Which not make a64 works.
I think I need to introduce a Sub SoC family.

**Comment by nandra** [comment]
> I think I need to introduce a Sub SoC family

Yes in this case. Thanks.

**Comment by nandra** [comment]
@clementperon can you pls post update for this machine, so we can merge it? Thanks.

**Comment by clementperon** [comment]
@nandra I don't have time at the moment. I will close it.

**Pull request closed without merging**
