### PR TITLE
linux: bump kernel version to 4.15

### PR DESCRIPTION
**Pull request by geomatsi**
Bump Linux kernel version to 4.15.

Notes:
- orange-pi-zero-plus2: drop patch fixing sdcard detect
  -- this fix is already in 4.15
- H2+/H3 SoCs: in 4.15 ethernet works right out of the box
  -- both sun8i emac driver and its DTS knobs has finally landed in mainline

Build-tested for the following platforms:
- pcduino
- orange-pi pc plus
- orange-pi zero
- orange-pi zero plus2
- orange-pi one
- nanopi-neo-air

Runtime tests of new images:
- orange-pi pc plus, orange-pi one, orange-pi zero plus2

Regards,
Sergey

### CODE REVIEW

**Comment by geomatsi** [comment]
Any comments on this ?

**Comment by macpijan** [comment]
I'm building 4.15.7 for `orange-pi-zero` myself:

```
SRCREV_pn-${PN} = "cb4a115a42867def71fdcbf0d7b714f268ff37fd"
KBRANCH = "linux-4.15.y"
```

Ethernet in fact works out of the box. Sometimes the board would not boot. Example dump:

```
[    3.248672] Unable to handle kernel NULL pointer dereference at virtual address 00000000
[    3.256903] pgd = d82af458
[    3.259636] [00000000] *pgd=00000000
[    3.263388] Internal error: Oops: 5 [#1] SMP ARM
[    3.268031] Modules linked in: autofs4
[    3.271827] CPU: 3 PID: 128 Comm: systemd-udevd Not tainted 4.15.7 #1
[    3.278285] Hardware name: Allwinner sun8i Family
[    3.283026] PC is at __fget+0x40/0x100
[    3.286807] LR is at __fget_light+0x88/0xd4
[    3.291016] pc : [<c02447e8>]    lr : [<c0244940>]    psr: 80010013
[    3.297305] sp : ce12def8  ip : 00000000  fp : 0000000e
[    3.302551] r10: c07cef4c  r9 : c07cef84  r8 : c0a5f522
[    3.307800] r7 : ce100200  r6 : 00004000  r5 : 00000000  r4 : 00000004
[    3.314340] r3 : cf9dc4c0  r2 : 00000004  r1 : 00004000  r0 : 00000004
[    3.320869] Flags: Nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[    3.328005] Control: 10c5387d  Table: 4e13006a  DAC: 00000051
[    3.333762] Process systemd-udevd (pid: 128, stack limit = 0x9c6cd830)
[    3.340290] Stack: (0xce12def8 to 0xce12e000)
[    3.344649] dee0:                                                       ce100200 00000004
[    3.352829] df00: 00000051 0048236c 000000fb 00000001 00000003 00000000 0000000e c0244940
[    3.361008] df20: 00000004 00000051 0048236c c02697f0 00000000 c0701d88 ce12df8c c0653170
[    3.369187] df40: ce12c000 a0010193 c0956b40 c0a05e38 ce12df74 c01503bc c09566fc c0653678
[    3.377366] df60: 00000003 d0802000 ce12dfb0 ffffe000 00000001 00000000 00000003 00000000
[    3.385545] df80: ce12c000 be9340a0 00000004 0048236c 000000fb c0107b64 ce12c000 00000000
[    3.393724] dfa0: 0000000e c0107980 be9340a0 00000004 00000004 00000001 00000003 be9340a0
[    3.401902] dfc0: be9340a0 00000004 0048236c 000000fb 0048e91c 00000003 00482360 0000000e
[    3.410082] dfe0: 00480ec4 be93401c 0045ba14 b6deb60c 20010010 00000004 00000000 00000000
[    3.418282] [<c02447e8>] (__fget) from [<c0244940>] (__fget_light+0x88/0xd4)
[    3.425345] [<c0244940>] (__fget_light) from [<c02697f0>] (SyS_epoll_ctl+0x88/0xaa8)
[    3.433103] [<c02697f0>] (SyS_epoll_ctl) from [<c0107980>] (ret_fast_syscall+0x0/0x54)
[    3.441029] Code: e1a06001 e5937410 e5975014 e1a02004 (e5951000) 
[    3.447195] ---[ end trace 23bc68d23102fff4 ]---
[    3.465526] BUG: Bad rss-counter state mm:63a2c174 idx:0 val:13
```

**Comment by geomatsi** [comment]
Hello @macpijan 
I have no idea what could be the reason of this particular crash on your setup. I haven't been using autofs4 in my tests. Both yocto/systemd and buildroot/sysinit images with 4.15 kernels looked good. So far all my crashes on that orange-pi-zero board were because of xr819 wireless driver.

Regards,
Sergey

**Comment by ebutera** [comment]
i'm merging this, @macpijan if the problem is related to the kernel please open an issue so we can track it

**Pull request merged**
