### PR TITLE
Upstream u-boot recipe

### PR DESCRIPTION
**Pull request by whirm**
I'm not so sure about the UBOOT_MACHINE var change. I was thinking about automatically updating the value on the new recipe if it has the old form (as in replacing _config with _defconfig).

What do you think?

(Also, newbie here, so any improvement you can suggest will be gladly accepted :))

### CODE REVIEW

**Comment by Noxenious** [comment]
Hi

I was also working on a mainline U-Boot recipe but did not have the time to finish it. Maybe we can work together on this to finish it:

- No need to change the _config to _defconfig so leave the machine configs alone.
- I was trying to support sunxi-uboot as well as mainline u-boot, which i prepared by adding a preferred provider to the sunxi.inc. If you name your new recipe like u-boot-mainline_2015.07rc1.bb you won´t break existing configs and can switch by changing the preferred provider.

 - Two boards use different config names in u-boot so add to your u-boot bb:
# Mainline U-Boot uses different names for some boards
UBOOT_MACHINE_olinuxino-a20 = "A20-OLinuXino_MICRO_config"
UBOOT_MACHINE_olinuxino-a10s = "A10s-OLinuXino-M_config"

- Mainline U-Boot will not boot the sunxi 3.4 kerne without patching as far as I know? Have you tried it?

**Comment by slapin** [comment]
Could you please do the same thing for kernel?
Will appreciate this.

**Comment by whirm** [comment]
@Noxenious I'll update the PR with your comments ASAP.

@slapin I already have WIP recipes for the 4.0 kernel on my repo, I was waiting for this one to go trough before submiting the kernel ones as they will need some updates if the u-boot recipe changes too much. But in the meanwhile you can try to use my layer which contains a working version of both. 
https://github.com/whirm/meta-sunxi/commits/master
(only tested on the cubieboard 2 though)
I'll check if I still have something pending to push that you may need later.

**Comment by whirm** [comment]
@Noxenious I'm rebuilding the whole thing to make sure it still works.

re old kernel: The wiki says it should work with a recent ```stage/sunxi-3.4``` build. 
I'm submiting a kernel 4.0 bb PR and some updates to the image builder after the u-boot one gets accepted. I'm not really interested in running 3.4 and people can still use the old u-boot if they want to use the old kernel. So it's not a big loss.

**Comment by whirm** [comment]
Ok, it built successfully.

**Comment by Noxenious** [comment]
I´ve just added a pull request for my mainline linux recipe which includes the device tree functions from openembedded / yocto. Can you try my recipe or do you see any disadvantages to your recipe?

**Comment by whirm** [comment]
@Noxenious I'll comment on that PR

**Comment by Noxenious** [comment]
I just tried your latest version and it does not build for me. I went back to 2015.04 and it works. Any idea why? Could we stay with the released version 2015.04 until 2015.07 is released?

|   CHK     include/config/uboot.release
|   CHK     include/generated/timestamp_autogenerated.h
| ./scripts/dtc-version.sh: line 17: dtc: command not found
|   UPD     include/config/uboot.release
|   UPD     include/generated/timestamp_autogenerated.h
| ./scripts/dtc-version.sh: line 18: dtc: command not found
| *** Your dtc is too old, please upgrade to dtc 1.4 or newer
| make: *** [checkdtc] Error 1

**Comment by Noxenious** [comment]
If I look at your commit there are 3 files for u-boot

u-boot_2015.07-rc1+git.bb
u-boot-mainline_2015.07rc1.bb
u-boot_git.bb

I think u-boot_2015.07-rc1+git.bb can be deleted?

**Comment by Noxenious** [comment]
Some suggestion: I would leave the DEFAULT_PREFERENCE within the u-boot files. The old sunxi u-boot will not change and the mainline u-boot will get entries added and it´s just another additional file to edit when adding another board.

**Comment by whirm** [comment]
@Noxenious oops, yes, that was a commit error. 

re dtc error: A dependency was missing on the recipe, should work fine now.

**Comment by naguirre** [comment]
If u-boot mainline offers the same functions or more than the actual u-boot revision, we can use it as default.
In case of linux kernel it's a bit different, as i doubt that the OpenGL ES part is working with mainline kernel.

**Comment by whirm** [comment]
@naguirre according to the wiki (https://linux-sunxi.org/Mainline_U-boot) u-boot mainline can't boot some old kernels is that OK?

**Comment by naguirre** [comment]
If I remember correctly, the current u-boot doesn't boot from nand and doesn't boot old kernel also.
So it's ok for me

**Comment by Noxenious** [comment]
The old kernel still supports some functions that mainline doesn´t, so I would keep that.

Mainline U-Boot can boot the latest sunxi 3.4 kernel (but see my cgroups issue there), but a config option in the defconfig for all boards is needed:

CONFIG_OLD_SUNXI_KERNEL_COMPAT=y

**Comment by ebutera** [comment]
if that config option has no side effects then we can just enable it.
In my opinion, the layer default config should be to use latest stable u-boot and latest kernel. Even if doesn't have all the features we should push people to use it.
Note: i never use the opengl/mali stuff, so i don't know if defaulting to recent kernels will break the builds. In that case we should stay with 3.4...

Anyway we shouldn't delete the old recipes, so if someone needs the older kernel/u-boot he can always change the DEFAULT_PREFERENCEs.

**Comment by whirm** [comment]
According to the docs:
```
Set this to enable various workarounds for old kernels, this results in                                                                                │
sub-optimal settings for newer kernels, only enable if needed.
```

**Comment by Noxenious** [comment]
Just tested your latest patches and everything works fine so far.

Sorry for having yet another comment :-)

about boot.cmd and this two lines:
load mmc 0:1 ${fdt_addr_r} ${fdtfile} || load mmc 0:1 ${fdt_addr_r} boot/${fdtfile}
load mmc 0:1 ${kernel_addr_r} zImage || load mmc 0:1 ${kernel_addr_r} boot/zImage || load mmc 0:1 ${kernel_addr_r} uImage || load mmc 0:1 ${kernel_addr_r} boot/uImage

The first partition is the fat32 partition created by the sunxi-sdimage. All files are put in the main directory. The second possibility is, that the files are within the main image on partition 2 which is a ext3 filesystem. So wouldn´t it make more sense to do:

load mmc 0:1 ${fdt_addr_r} ${fdtfile} || ext2load mmc 0:2 ${fdt_addr_r} boot/${fdtfile}
load mmc 0:1 ${kernel_addr_r} zImage || ext2load mmc 0:2 ${kernel_addr_r} boot/zImage || load mmc 0:1 ${kernel_addr_r} uImage || ext2load mmc 0:2 ${kernel_addr_r} boot/uImage

**Comment by whirm** [comment]
@Noxenious It makes sense. I don't mind either way as I only use the first case (That's a direct copypaste from the wiki).
@naguirre what do you say?

**Comment by naguirre** [comment]
I prefer fat32 and not change the sdcard class too much in this PR.

**Comment by whirm** [comment]
@naguirre should I remove the ```classes/sdcard_image-sunxi.bbclass``` patch from this one then?

**Comment by naguirre** [comment]
no, it's good as long as you keep fat32.

**Comment by whirm** [comment]
@naguirre so the only thing left is to rename u-boot-mainline_2015.07rc1.bb to u-boot_2015.07rc1.bb and remove the DEFAULT_PREFERENCEs from the old recipe to give this one precedence? (I'm not yet quite familiar with the priority stuff)

**Comment by Noxenious** [comment]
No not exactly. There are four possibilities:

1) Rename u-boot-mainline_2015.07rc1.bb to u-boot_2015.07rc1.bb and current u-boot_git.bb to u-boot-sunxi.bb. Default will be mainline, one can switch back to sunxi u-boot by setting "PREFERRED_PROVIDER_u-boot" and "PREFERRED_PROVIDER_virtual/bootloader" to u-boot-sunxi (in file sunxi.inc)

2) Rename u-boot-mainline_2015.07rc1.bb to u-boot_2015.07rc1.bb and current u-boot_git.bb to u-boot-sunxi.bb.Setting "PREFERRED_PROVIDER_u-boot" and "PREFERRED_PROVIDER_virtual/bootloader" to u-boot-sunxi (in file sunxi.inc), so default will be u-boot-sunxi. One can change to mainline by setting PREFERRED_PROVIDER to u-boot.

3) Leave the current names. Default will be u-boot-sunxi. Can be changed by setting PREFERRED_PROVIDER to u-boot-mainline.

4) Leave the current names, set PREFERRED_PROVIDER to u-boot-mainline so it will be default.

It all depends if mainline should be default or not. Please note that when applying this and settings u-boot to default mainline we also need mainline linux. I think I have sorted it out, I will push my final patch later this evening.

**Comment by Noxenious** [comment]
Otherwise I am happy with this and have tested it. Maybe bump to rc2 before merging?

**Pull request merged**
