### PR TITLE
linux-mainline: fix 'devtool modify' command fail

### PR DESCRIPTION
**Pull request by qpmr**
Traceback (most recent call last):
  File "${TOPDIR}/../src/poky/scripts/devtool", line 338, in <module>
    ret = main()
  File "${TOPDIR}/../src/poky/scripts/devtool", line 325, in main
    ret = args.func(args, config, basepath, workspace)
  File "${TOPDIR}/../src/poky/scripts/lib/devtool/standard.py", line 834, in modify
    if (os.path.exists(srcdir) and os.listdir(srcdir)) and (kernelVersion in staging_kerVer and staging_kbranch == kbranch):
TypeError: 'in <string>' requires string as left operand, not NoneType

Where 'kernelVersion' is None that cause an error.
In the code: "kernelVersion = rd.getVar('LINUX_VERSION')"
So LINUX_VERSION should be initialized

Signed-off-by: Ilja Byckevich <iljabyckevich@gmail.com>

### CODE REVIEW

**Comment by nandra** [comment]
Thanks for the patch.

Wouldn't it be easier to add to linux-mainline.inc line:
`LINUX_VERSION = "${PV}"` ? Should work. Thanks.

**Comment by qpmr** [comment]
> Thanks for the patch.
> 
> Wouldn't it be easier to add to linux-mainline.inc line: `LINUX_VERSION = "${PV}"` ? Should work. Thanks.

Yes, I've been thinking about it. But more widely this variable is used in the format "x.x.x" (yes, yes, in these cases the name of the recipe is different, for example "linux-yocto_5.10.bb ". Docs also use 'x.x.x'). But I think it's more "humanly", familiar and, perhaps, convenient in the future :)

**Comment by nandra** [comment]
All our recipes are used in this way like:
```
linux-mainline_5.10.2.bb
linux-mainline_5.15.35.bb
linux-mainline_5.4.69.bb
```
so making it automatic is preferable to me as I tend to forget update something in recipe when bumping it what is hardcoded internally ;)

**Comment by nandra** [comment]
Thanks, merged.

**Comment by qpmr** [comment]
> All our recipes are used in this way like:
> 
> ```
> linux-mainline_5.10.2.bb
> linux-mainline_5.15.35.bb
> linux-mainline_5.4.69.bb
> ```
> 
> so making it automatic is preferable to me as I tend to forget update something in recipe when bumping it what is hardcoded internally ;)

Well, in this case  I agree with you, updated : )

**Pull request merged**
